### ISSUE TITLE
Why self.train_batch() function dosen't have a specific implementation?

### ISSUE THREAD

**Issue by supremewu11** [marcelampc/mtl_aerial_images#7]
https://github.com/marcelampc/aerial_mtl/blob/c6a2033ec89a89ff06836014c619d66bc907d958/models/train_model.py#L122
<img width="424" alt="截屏2024-03-20 18 07 46" src="https://github.com/marcelampc/aerial_mtl/assets/59760129/74e939f4-c59a-4431-a52d-5b9c53baed97">

**Comment by marcelampc** [comment]
Hello, it's been a while since I worked on this project. This is an abstract class, so for this function, I've just established here that it should be implemented for each other class that inherits from it. For example, models/mtl_train.py has an implementation to it.

As I look into this code now, years later, I see it could benefit from a good refactor =)

**Comment by supremewu11** [comment]
Thank you very much for replying me in time, and I can benefit from your code also =)
